---

##
## IN THIS FILE
##
## This mapping table is used by the module MMT::TranslationTable::FineType
## it defines mappings from voyager.fine_fee.fine_fee_type to koha.accountlines.accounttype
##


#voyager.FINE_FEE_TYPE.csv
#FINE_FEE_TYPE,               FINE_FEE_DESC, FINE_FEE_CODE
#   mapping
1:  O                        #"Overdue","F1"
2:  L                        #"Lost Item Replacement", "F2"
3:  L                        #"Lost Item Processing", "F3"
4:  F                        #"Media Booking Late Charge","F4"
5:  Rent                     #"Media Booking Usage Fee","F5"
6:  Rep                      #"Equipment Replacement","F6"
7:  L                        #"Lost Equipment Processing","F7"
8:  F                        #"Accrued Fine","F8"
9:  F                        #"Accrued Demerit","F9"
10: F                        #"Demerit","F10"
11: F                        #"Myohastymismaksu","RenameF8"
13: Kauko                    #"Kaukolaina","RenameF10"
12: N                        #"Kirjastokortti","RenameF9"
14: M                        #"Kï¿½sittelymaksu","F11"
15: ODUEC                    #"Laskutettu","F12"
16: HE                       #"Noutamaton varaus","F13"
17: HE                       #"Noutamaton kaukolaina","F14"
18: F                        #"Lyhytlaina -1. pv (5 eur)","F15"
19: F                        #"Lyhytlaina -muut (1 eur)","F16"

# For values in Koha, see. https://wiki.koha-community.org/wiki/Hard_Coded_Values
