---

##
## IN THIS FILE
##
## This mapping table is used by the module MMT::TranslationTable::ItemTypes
## it defines mappings from voyager.item.item_type_id integer to koha.items.itype
##

#voyager.ITEM_TYPE
#ITEM_TYPE_ID       ,ITEM_TYPE_CODE, ITEM_TYPE_NAME, ITEM_TYPE_DISPLAY
#2: KI #28vrk, "Laina 28 vrk","Laina-aika 28 vrk"
#3: KI #0vrk, "Ei kotilainaan","Ei kotilainaan"
#4: KI #180vrk, "Erityislaina 0/28/180 vrk","180 vrk"
#5: KI #s0vrk, "Suljettu varasto 0vrk","Suljettu varasto, ei kotilainaan"
#6: KI #84vrk, "84vrk","Laina-aika 84 vrk"
#7: KU #K2vrk, "Kurssikirja 2 vrk","Kurssikirja, laina-aika 2 vrk"
#8: KI #7vrk, "7 vrk laina","Laina-aika 7 vrk"
#9: KI #14vrk, "Laina 14 vrk","Laina-aika 14 vrk"
#10: KI #1vrk, "1 vrk:n laina","1 vuorokauden laina"
#11: KU #K1vrk, "Kurssikirja laina 1 vrk","Kurssikirja, laina-aika 1 vrk"
#12: KU #K7vrk, "Kurssikirja laina 7 vrk","Kurssikirja, laina-aika 7 vrk"
#13: KU #K14vrk, "Kurssik Hb Sk 14 vrk","Kurssikirja, laina-aika 14 vrk"
#14: PO #P0vrk, "P0vrk","P 0 vrk"
#15: KU #k14vrk, "Kurssikirja laina 14 vrk","Kurssikirja, laina-aika 14 vrk"
#16: KU #K0vrk, "Kurssikirja 0 vrk","Kurssikirja, ei kotilainaan"
#17: KU #K28vrk, "Kurssikirja laina 28 vrk","Kurssikirja, laina-aika 28 vrk"
#18: KI #s28vrk, "Suljettu varasto laina 28","Suljettu varasto, laina-aika 28 vrk"
#19: KI #s7vrk, "Suljettu varasto 7 vrk","Suljettu varasto, laina-aika 7 vrk"
#20: KU #k1vrk, "Kurssikirja 1 vrk","Kurssikirja, laina-aika 1 vrk"
#24: KU #Klukukausi, "Kurssikirja lukukausi","Kurssikirja, lukukausilaina"
#25: KI #2vrk, "2 vrk:n laina","Laina-aika 2 vrk"
#1: REVIEW #REVIEW, "REVIEW","REVIEW"
#26: TK #tietokone, "Lainattava mikrotietokone","Lainattava mikrotietokone"
#23: HC #Hctemp, "zHc temp","Laina-aika 28 vrk"
#29: KI #s14vrk, "Suljettu varasto 14 vrk","Suljettu varasto, laina-aika 14 vrk"
#27: ES #EsineA, "Esinelaina A","Esinelaina"
#28: ES #EsineB, "Esinelaina B","Esinelaina"

1:
2:
3:
4:
5:
6:
7:
8:
9:
10:
11:
12:
13:
14:
15:
16:
17:
18:
19:
20
21:
22:
23:
24:
25: 
26:
27:
28:

# If you have mappings such as these, one should carefully consider to instead use item type as a
# description of the Item's external appearance. Koha has many levels to organize and categorize items
# and their respective circulation rules
