---

##
## IN THIS FILE
##
## This mapping table is used by the module MMT::TranslationTable::ItemTypes
## it defines mappings from voyager.item.item_type_id integer to koha.items.itype
##

#voyager.ITEM_TYPE
#ITEM_TYPE_ID       ,ITEM_TYPE_CODE, ITEM_TYPE_NAME, ITEM_TYPE_DISPLAY
1: RV #"REVIEW","REVIEW","REVIEW"
2: AR #"Article","Article","Article"
3: BK #"Book","Book","Book"
4: SR #"Serial","Serial","Serial"

# If you have mappings such as these, one should carefully consider to instead use item type as a
# description of the Item's external appearance. Koha has many levels to organize and categorize items
# and their respective circulation rules
