##  branchLoc-sulkujen väliin tulee alla olevan rivin mukaiset sijainnit kohassa, pilkulla eroteltuna, samalla tavalla kuin _DEFAULT_ rivillä.
##  branchcode, shelving_location, collection_code, sub_location, item.itemtype, item.notforloan-status

1:   branchLoc()		#REVIEW    ,REVIEW
+REVIEW: ref(1)
2:   branchLoc()		#mettiHA   ,Arabia hankinta
+mettiHA: ref(2)
3:   branchLoc()		#metleHA   ,Leppävaara hankinta
+metleHA: ref(3)
4:   branchLoc()		#metmyHA   ,Myyrmäki hankinta
+metmyHA: ref(4)
5:   branchLoc()		#mettuLUKU ,Tukholmankatu lukusali
+mettuLUKU: ref(5)
6:   branchLoc()		#metagYK   ,Agricolankatu yleiskok.
+metagYK: ref(6)
7:   branchLoc()		#metagONT  ,Agricolankatu opinnäytet.
+metagONT: ref(7)
8:   branchLoc()		#metagCDROM,Agricola CD-ROM
+metagCDROM: ref(8)
9:   branchLoc()		#metagAV   ,Agricola videot
+metagAV: ref(9)
10:  branchLoc()		#metagKK   ,Agricolankatu käsikirjat
+metagKK: ref(10)
11:  branchLoc()		#metagLEH  ,Agricolankatu lehdet
+metagLEH: ref(11)
12:  branchLoc()		#metagTYO  ,Agricolankatu työhuone
+metagTYO: ref(12)
14:  branchLoc()		#metagHA   ,Agricolankatu hankinta
+metagHA: ref(14)
15:  branchLoc()		#metbuYK   ,Bulevardi yleiskokoelma
+metbuYK: ref(15)
16:  branchLoc()		#metbuONT  ,Bulevardi opinnäytetyöt
+metbuONT: ref(16)
17:  branchLoc()		#metbuCDROM,Bulevardi CD-ROM
+metbuCDROM: ref(17)
18:  branchLoc()		#metbuKK   ,Bulevardi käsikirjat
+metbuKK: ref(18)
20:  branchLoc()		#metbuLEH  ,Bulevardi lehdet
+metbuLEH: ref(20)
21:  branchLoc()		#metbuTYO  ,Bulevardi työhuone
+metbuTYO: ref(21)
24:  branchLoc()		#REMOVED   ,REMOVED
+REMOVED: ref(24)
25:  branchLoc()		#mettiAV   ,Arabia AV-aineisto
+mettiAV: ref(25)
26:  branchLoc()		#mettiKK   ,Arabia käsikirjat
+mettiKK: ref(26)
27:  branchLoc()		#mettiYK   ,Arabia yleiskokoelma
+mettiYK: ref(27)
28:  branchLoc()		#mettiONT  ,Arabia opinnäytetyöt
+mettiONT: ref(28)
29:  branchLoc()		#metleCDROM,Leppävaara CD-ROM
+metleCDROM: ref(29)
30:  branchLoc()		#metleKK   ,Leppävaara käsikirjat
+metleKK: ref(30)
32:  branchLoc()		#metleONT  ,Leppävaara opinnäytetyöt
+metleONT: ref(32)
33:  branchLoc()		#metleVAR  ,Leppävaara varasto
+metleVAR: ref(33)
34:  branchLoc()		#metleAV   ,Leppävaara videot
+metleAV: ref(34)
35:  branchLoc()		#metleVIR  ,Leppävaara virkailija
+metleVIR: ref(35)
36:  branchLoc()		#metleYK   ,Leppävaara yleiskokoelma
+metleYK: ref(36)
37:  branchLoc()		#metmyCDROM,Myyrmäki palvelutiski
+metmyCDROM: ref(37)
38:  branchLoc()		#metmyKK   ,Myyrmäki käsikirjat
+metmyKK: ref(38)
39:  branchLoc()		#metmyLYHYT,Myyrmäki viikon laina
+metmyLYHYT: ref(39)
40:  branchLoc()		#metmyONT  ,Myyrmäki opinnäytetyöt
+metmyONT: ref(40)
41:  branchLoc()		#metmyVAR  ,Myyrmäki varasto
+metmyVAR: ref(41)
42:  branchLoc()		#metmyAV   ,Myyrmäki videot
+metmyAV: ref(42)
43:  branchLoc()		#metmyYK   ,Myyrmäki yleiskokoelma
+metmyYK: ref(43)
44:  branchLoc()		#metonYK   ,Onnentie yleiskokoelma
+metonYK: ref(44)
45:  branchLoc()		#metonONT  ,Onnentie opinnäytetyöt
+metonONT: ref(45)
46:  branchLoc()		#metonAV   ,Onnentie videot
+metonAV: ref(46)
47:  branchLoc()		#metonKK   ,Onnentie käsikirjat
+metonKK: ref(47)
48:  branchLoc()		#metonLEH  ,Onnentie lehdet
+metonLEH: ref(48)
50:  branchLoc()		#metsoYK   ,Arabia var yleiskokoelma
+metsoYK: ref(50)
51:  branchLoc()		#metsoONT  ,Sofianlehto opinnäytetyöt
+metsoONT: ref(51)
52:  branchLoc()		#metsoCDROM,Sofianlehto CD-ROM
+metsoCDROM: ref(52)
53:  branchLoc()		#metsoAV   ,Sofianlehto videot
+metsoAV: ref(53)
54:  branchLoc()		#metsoKK   ,Sofianlehto käsikirjat
+metsoKK: ref(54)
55:  branchLoc()		#metsoLEH  ,Sofianlehto lehdet
+metsoLEH: ref(55)
57:  branchLoc()		#mettuONT  ,Tukholmankatu opinnäytety
+mettuONT: ref(57)
58:  branchLoc()		#mettuCDROM,Tukholmankatu CD-ROM
+mettuCDROM: ref(58)
59:  branchLoc()		#mettuAV   ,Tukholmankatu videot
+mettuAV: ref(59)
61:  branchLoc()		#mettuVAR  ,Arabia varasto (Tukho var
+mettuVAR: ref(61)
65:  branchLoc()		#mettuHA   ,Tukholmankatu hankinta
+mettuHA: ref(65)
66:  branchLoc()		#metviYK   ,Viertotie yleiskokoelma
+metviYK: ref(66)
68:  branchLoc()		#metviCDROM,Viertotie CD-ROM
+metviCDROM: ref(68)
70:  branchLoc()		#metviAANI ,Viertotie aanitteet
+metviAANI: ref(70)
71:  branchLoc()		#metviKK   ,Viertotie käsikirjat
+metviKK: ref(71)
74:  branchLoc()		#metviOPEMA,Viertotie opetusmat.
+metviOPEMA: ref(74)
75:  branchLoc()		#metbuHA   ,Bulevardi hankinta
+metbuHA: ref(75)
76:  branchLoc()		#metonHA   ,Onnentie hankinta
+metonHA: ref(76)
77:  branchLoc()		#metsoHA   ,Sofianlehto hankinta
+metsoHA: ref(77)
78:  branchLoc()		#metviHA   ,Viertotie hankinta
+metviHA: ref(78)
79:  branchLoc()		#metagLU   ,Agricola luettelointi
+metagLU: ref(79)
80:  branchLoc()		#metbuLU   ,Bulevardi luettelointi
+metbuLU: ref(80)
81:  branchLoc()		#metleLU   ,Leppävaara luettelointi
+metleLU: ref(81)
82:  branchLoc()		#metmyLU   ,Myyrmäki luettelointi
+metmyLU: ref(82)
83:  branchLoc()		#metonLU   ,Onnentie luettelointi
+metonLU: ref(83)
84:  branchLoc()		#metsoLU   ,Sofianlehto luettelointi
+metsoLU: ref(84)
85:  branchLoc()		#mettiLU   ,Arabia luettelointi
+mettiLU: ref(85)
86:  branchLoc()		#mettuLU   ,Tukholmank luettelointi
+mettuLU: ref(86)
87:  branchLoc()		#metviLU   ,Viertotie luettelointi
+metviLU: ref(87)
60:  branchLoc()		#mettuKK   ,Tukholmankatu käsikirjat
+mettuKK: ref(60)
63:  branchLoc()		#mettuLEH  ,Tukholmankatu lehdet
+mettuLEH: ref(63)
64:  branchLoc()		#mettuTYO  ,Tukholmankatu työhuone
+mettuTYO: ref(64)
62:  branchLoc()		#mettuVARLE,Tukholmank lehdet varasto
+mettuVARLE: ref(62)
56:  branchLoc()		#mettuYK   ,Arabia varasto yleiskok.
+mettuYK: ref(56)
69:  branchLoc()		#metviAV   ,Viertotie videot
+metviAV: ref(69)
73:  branchLoc()		#metviLEH  ,Viertotie lehdet
+metviLEH: ref(73)
67:  branchLoc()		#metviONT  ,Viertotie opinnäytetyöt
+metviONT: ref(67)
72:  branchLoc()		#metviVAR  ,Viertotie varasto
+metviVAR: ref(72)
23:  branchLoc()		#metWWW    ,Verkkoaineisto
+metWWW: ref(23)
143: branchLoc()		#metmpLA   ,Myllypuro lainaus
+metmpLA: ref(143)
144: branchLoc()		#metmpYK   ,Myllypuro yleiskokoelma
+metmpYK: ref(144)
117: branchLoc()		#metleINV  ,Inventaario/Leppavaara
+metleINV: ref(117)
118: branchLoc()		#mettuINV  ,Inventaario Tukho
+mettuINV: ref(118)
126: branchLoc()		#mettiPIKA ,Arabia pikalainat
+mettiPIKA: ref(126)
128: branchLoc()		#MAKSU     ,Verkkomaksaminen
+MAKSU: ref(128)
131: branchLoc()		#mettiAANI ,Arabia äänitteet
+mettiAANI: ref(131)
132: branchLoc()		#mettiNUO  ,Arabia nuotit
+mettiNUO: ref(132)
133: branchLoc()		#mettiNUOKK,Arabia nuottikäsikirjasto
+mettiNUOKK: ref(133)
134: branchLoc()		#mettiORK  ,Arabia orkesterimateriaal
+mettiORK: ref(134)
135: branchLoc()		#mettiPAR  ,Arabia partituurit
+mettiPAR: ref(135)
136: branchLoc()		#mettiJOULU,Arabia joulumateriaali
+mettiJOULU: ref(136)
145: branchLoc()		#metmpPIKA ,Myllypuro viikon laina
+metmpPIKA: ref(145)
146: branchLoc()		#metmpONT  ,Myllypuro opinnäytteet
+metmpONT: ref(146)
147: branchLoc()		#metmpLU   ,Myllypuro luettelointi
+metmpLU: ref(147)
148: branchLoc()		#metmpKK   ,Myllypuro käsikirjat
+metmpKK: ref(148)
149: branchLoc()		#metmpLEH  ,Myllypuro lehdet
+metmpLEH: ref(149)
150: branchLoc()		#metmpHA   ,Myllypuro hankinta
+metmpHA: ref(150)
151: branchLoc()		#metmpAU   ,Myllypuro automaatti
+metmpAU: ref(151)
120: branchLoc()		#metmyINV  ,Myyrmäki INVENTAARIO
+metmyINV: ref(120)
116: branchLoc()		#metbuINV  ,Inventaario BULE
+metbuINV: ref(116)
122: branchLoc()		#mettuPIKA ,Arabia var viikon laina
+mettuPIKA: ref(122)
124: branchLoc()		#metsoERI  ,Varasto, erikoiskokoelma
+metsoERI: ref(124)
115: branchLoc()		#metsoAANI ,Sofianlehto äänitteet
+metsoAANI: ref(115)
127: branchLoc()		#metmaLA   ,Mannerheimintie lainaus
+metmaLA: ref(127)
129: branchLoc()		#metruLA   ,Ruoholahti lainaus
+metruLA: ref(129)
88:  branchLoc()		#metleLEH  ,Leppävaara lehdet
+metleLEH: ref(88)
89:  branchLoc()		#metmyLEH  ,Myyrmäki lehdet
+metmyLEH: ref(89)
90:  branchLoc()		#mettiLEH  ,Arabia lehdet
+mettiLEH: ref(90)
91:  branchLoc()		#metagLA   ,Agricolankatu lainaus
+metagLA: ref(91)
92:  branchLoc()		#metbuLA   ,Bulevardi lainaus
+metbuLA: ref(92)
93:  branchLoc()		#metleLA   ,Leppävaara lainaus
+metleLA: ref(93)
94:  branchLoc()		#metmyLA   ,Myyrmäki lainaus
+metmyLA: ref(94)
95:  branchLoc()		#metonLA   ,Onnentie lainaus
+metonLA: ref(95)
96:  branchLoc()		#metsoLA   ,Sofianlehdonkatu lainaus
+metsoLA: ref(96)
97:  branchLoc()		#mettiLA   ,Arabia lainaus
+mettiLA: ref(97)
98:  branchLoc()		#mettuLA   ,Tukholmankatu lainaus
+mettuLA: ref(98)
99:  branchLoc()		#metviLA   ,Viertotie lainaus
+metviLA: ref(99)
100: branchLoc()		#metagAU   ,Agricolankatu automaatti
+metagAU: ref(100)
101: branchLoc()		#metbuAU   ,Bulevardi automaatti
+metbuAU: ref(101)
102: branchLoc()		#metleAU   ,Leppävaara automaatti
+metleAU: ref(102)
103: branchLoc()		#metmyAU   ,Myyrmäki automaatti
+metmyAU: ref(103)
104: branchLoc()		#metonAU   ,Onnentie automaatti
+metonAU: ref(104)
105: branchLoc()		#metsoAU   ,Sofianlehto automaatti
+metsoAU: ref(105)
106: branchLoc()		#mettiAU   ,Arabia automaatti
+mettiAU: ref(106)
107: branchLoc()		#mettuAU1  ,Tukholmankatu automaatti1
+mettuAU1: ref(107)
108: branchLoc()		#mettuAU2  ,Tukholmankatu automaatti2
+mettuAU2: ref(108)
109: branchLoc()		#metviAU   ,Viertotie automaatti
+metviAU: ref(109)
110: branchLoc()		#metmyAU2  ,Myyrmäki automaatti2
+metmyAU2: ref(110)
113: branchLoc()		#mettuAANI ,Tukholmankatu äänitteet
+mettuAANI: ref(113)
114: branchLoc()		#LASKUTETTU,Laskutettu aineisto
+LASKUTETTU: ref(114)
119: branchLoc()		#metsoINV  ,Inventaario Soffari
+metsoINV: ref(119)
121: branchLoc()		#metmyVIR  ,Myyrmäki Virkailija
+metmyVIR: ref(121)
123: branchLoc()		#metsoPIKA ,Arabia var. viikon laina
+metsoPIKA: ref(123)
125: branchLoc()		#metmaKK   ,Mannerheimintie käsikirja
+metmaKK: ref(125)
130: branchLoc()		#metroDB   ,E-aineistot
+metroDB: ref(130)
142: branchLoc()		#metmyAU3  ,Myyrmäki automaatti3
+metmyAU3: ref(142)
137: branchLoc()		#metagPIKA ,Agricolank. viikon laina
+metagPIKA: ref(137)
138: branchLoc()		#metbuPIKA ,Bulevardi viikon laina
+metbuPIKA: ref(138)
139: branchLoc()		#metlePIKA ,Leppävaara viikon laina
+metlePIKA: ref(139)
140: branchLoc()		#metviPIKA ,Viertotie viikon laina
+metviPIKA: ref(140)
141: branchLoc()		#metagINV  ,Inventaario Agri
+metagINV: ref(141)

_DEFAULT_: branchLoc(KONVERSIO, KONVERSIO, KONVERSIO, KONVERSIO) #Oletusarvot / paikkaansa löytämättömät

